<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Chris82111.$(SolutionName).$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <Version>1.0.0</Version>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageId>Chris82111.$(SolutionName).$(MSBuildProjectName.Replace(" ", "_"))</PackageId>
    <Authors>Chris82111</Authors>
    <Company>GitManager</Company>
    <RepositoryUrl>https://github.com/Chris82111/GitManager</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Git;Portable;Static;Linux;Windows</PackageTags>
    <Product>GitManager</Product>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Copyright (c) Chris82111 2025</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Description>Plugin to extend the Core solution for using Git in a portable form.

Supports:
- Linux X64
- Windows X64</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitWrapper.Core\GitWrapper.Core.csproj" />
    <ProjectReference Include="..\GitWrapper.Static.LinuxX64\GitWrapper.Static.LinuxX64.csproj" />
    <ProjectReference Include="..\GitWrapper.Static.WindowsX64\GitWrapper.Static.WindowsX64.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
    <None Include="LICENSE" Pack="true" PackagePath="/" />
    <None Include="THIRD_PARTY_LICENSES" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
