<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Chris82111.$(SolutionName).$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <UseNuGetPackages>false</UseNuGetPackages>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseNuGetPackages)' != 'true'">
    <ProjectReference Include="..\GitWrapper.Static.LinuxX64\GitWrapper.Static.LinuxX64.csproj" />
    <ProjectReference Include="..\GitWrapper.Static.WindowsX64\GitWrapper.Static.WindowsX64.csproj" />
    <ProjectReference Include="..\GitWrapper.Core\GitWrapper.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseNuGetPackages)' == 'true'">
    <PackageReference Include="Chris82111.GitManager.GitWrapper.Static.LinuxX64"
      Version="1.0.0-rc.1" />
    <PackageReference Include="Chris82111.GitManager.GitWrapper.Static.WindowsX64"
      Version="1.0.0-rc.1" />
    <PackageReference Include="Chris82111.GitManager.GitWrapper.Core"
      Version="1.0.0-rc.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
