<Project>
  
  <ItemGroup Condition="'true' == '$(EnableStaticGitUseLinux)' And 'true' == '$(UseGitLinux)'">
    <None
      Include="$(GitLinuxArchiveFileRelative)"
      Pack="true"
      PackagePath="$(GitLinuxRuntimeDirectory)" >
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup Condition="'true' == '$(EnableStaticGitUseLinux)' And 'false' == '$(UseGitLinux)'">
    <None
      Include="$(GitLinuxArchiveFileRelative)"
      Pack="true"
      PackagePath="$(GitLinuxRuntimeDirectory)" >
    </None>
  </ItemGroup>
  
  <Target Name="GitLinuxPropertyGroup"
    BeforeTargets="BeforeBuild;Pack" >
    
    <PropertyGroup>
    
    </PropertyGroup>
  
  </Target>
  
  <Target Name="GitLinuxBuild"
    AfterTargets="GitLinuxPropertyGroup"
    Outputs="$(GitLinuxArchiveFileRelative)"
    Condition="!Exists('$(GitLinuxArchiveFileRelative)') And 'true' == '$(EnableStaticGitUseLinux)'" >
    
    <Message Text="Git Linux  : Running Docker using: $(DockerCmd)" Importance="high" />
    
    
    <PropertyGroup>
      <DockerNoCache Condition="Exists('$(GitLinuxDockerNoCacheFile)')">true</DockerNoCache>
    </PropertyGroup>  
    
    <!-- Ensure directory exists -->
    <MakeDir
      Condition="!Exists('$(GitLinuxRuntimeDirectory)')"
      Directories="$(GitLinuxRuntimeDirectory)" />
    
    <!-- Removes the file -->
    <Delete
      Files="$(GitLinuxDockerNoCacheFile)" />
    
    <!-- Build Docker image without cache -->
    <Message
      Text="Docker cache invalidation requested."
      Condition="'true' == '$(DockerNoCache)'"
      Importance="high" />
    <Exec
      Command="$(DockerCmd) build --no-cache --progress=plain -t staticgitbuildtempimage ."
      WorkingDirectory="$(GitLinuxLibDirectory)"
      Condition="'true' == '$(DockerNoCache)'" />
    
    <!-- Build Docker image with cache -->
    <Message
      Text="Docker runs with cache."
      Condition="'true' != '$(DockerNoCache)'"
      Importance="high" />
    <Exec
      Command="$(DockerCmd) build --progress=plain -t staticgitbuildtempimage ."
      WorkingDirectory="$(GitLinuxLibDirectory)"
      Condition="'true' != '$(DockerNoCache)'" />
    
    <!-- Export files from the Docker image -->
      <!-- Small cleanup -->
      <Exec Command="$(DockerCmd) rm staticgitbuildexporttemp" IgnoreExitCode="true" />
      <!-- Create image -->
      <Exec Command="$(DockerCmd) create --name staticgitbuildexporttemp staticgitbuildtempimage" />
      <!-- Copy zip -->
      <Exec Command="$(DockerCmd) cp staticgitbuildexporttemp:$(GitLinuxDockerInternalZipFileFull) ./" WorkingDirectory="$(GitLinuxRuntimeDirectory)" />
      <!-- Small cleanup -->
      <Exec Command="$(DockerCmd) rm staticgitbuildexporttemp" />
  
  </Target>

  <Target Name="GitLinuxBuildCleanup"
    AfterTargets="GitLinuxBuild"
    Condition="Exists('$(GitLinuxArchiveFileRelative)')" >
      
    <!-- Removes the file -->
    <Delete
      Files="$(GitLinuxDockerNoCacheFile)" />
      
  </Target>
    
  <Target Name="GitLinuxCleanup" BeforeTargets="Clean" >
    <Exec Command="$(DockerCmd) rmi staticgitbuildtempimage" IgnoreExitCode="true" />
    
    <WriteLinesToFile
      File="$(GitLinuxDockerNoCacheFile)"
      Lines="1"
      Overwrite="true" />
    
    <!-- Do not remove, it is assumed that the exported file is error-free. -->
    <!-- RemoveDir Directories="$(GitLinuxRuntimeDirectory)" /-->
    
  </Target>
  
  <Target Name="GitLinuxGeneratePath" 
    BeforeTargets="CoreCompile;Pack"
    Inputs="$(GitLinuxLibRelative)"
    Outputs="$(ArchivePathsFileRelative)" >
    
    <PropertyGroup>
      <GitLinuxOutputArchiveFileRelativeForwardSlash>$([System.String]::Copy('$(GitLinuxOutputArchiveFileRelative)').Replace('\', '/'))</GitLinuxOutputArchiveFileRelativeForwardSlash>
      <GitLinuxOutputExecutableRelativeForwardSlash>$([System.String]::Copy('$(GitLinuxOutputExecutableRelative)').Replace('\', '/'))</GitLinuxOutputExecutableRelativeForwardSlash>
    </PropertyGroup>
    
    <WriteLinesToFile
        File="$(ArchivePathsFileRelative)"
        Overwrite="true"
        Lines='
// This code was generated by a tool in the file "$(MSBuildThisFile)".
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
namespace Chris82111.$(SolutionName).$(MSBuildProjectName.Replace(" ", "_")).Lib
{
    /// &lt;summary&gt;
    /// Paths and names to the archive
    /// &lt;/summary&gt;
    public static class ArchivePaths
    {
        /// &lt;summary&gt;
        /// Relative path to the archive
        /// &lt;/summary&gt;
        public const string ArchiveFileRelative = @"$(GitLinuxOutputArchiveFileRelativeForwardSlash)"%3B
        
        /// &lt;summary&gt;
        /// Relative path in the archive
        /// &lt;/summary&gt;
        public const string ExecutableRelative = @"$(GitLinuxOutputExecutableRelativeForwardSlash)"%3B
    }
}
' />
  
  <ItemGroup>
    <Compile Remove="$(ArchivePathsFileRelative)" />
    <Compile Include="$(ArchivePathsFileRelative)" />
  </ItemGroup>
  
  </Target>

</Project>